FROM quay.io/fedora/fedora:35 as fedora35
ARG OS_VERSION=35
ARG ARCH=x86_64
ARG BUILD_TOOLS="jq findutils yum-utils createrepo"

RUN yum update -y -q && yum install -y $BUILD_TOOLS && yum makecache

WORKDIR /fedora/$OS_VERSION/os/$ARCH

RUN curl -sL -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.25.2/yq_linux_amd64 && chmod a+x /usr/local/bin/yq

COPY packages.yaml packages.yaml

RUN yq eval packages.yaml -j | jq -r '.common[],.yum[],.fedora[]' | sort -u > packages.list #  && rpm -qa >> packages.list

RUN cat packages.list | xargs yumdownloader --resolve && createrepo -d .

FROM scratch

COPY --from=fedora35 /fedora /fedora
