FROM quay.io/fedora/fedora:36 as fedora36
ARG DISTRO=fedora
ARG OS_VERSION=36
ARG ARCH=x86_64
ARG BUILD_TOOLS="jq findutils yum-utils createrepo"

RUN yum update -y -q && yum install -y $BUILD_TOOLS && yum makecache

RUN curl -sL -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.25.2/yq_linux_amd64 && chmod a+x /usr/local/bin/yq

WORKDIR /$DISTRO-tmp

COPY * .

RUN ./packager.sh

WORKDIR /$DISTRO/$OS_VERSION/os/$ARCH

RUN yq eval /$DISTRO-tmp/packages.yaml -j | jq -r '.common[],.yum[],.fedora[]' | sort -u > packages.list #  && rpm -qa >> packages.list

RUN cat packages.list | xargs yumdownloader --resolve && createrepo -d .

FROM scratch

COPY --from=fedora36 /fedora /fedora
